AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A serverless deployment pipeline using Lambda, DynamoDB, S3, and other AWS services.

Resources:

  PipelineConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PipelineConfig
      AttributeDefinitions:
        - AttributeName: pipeline_id
          AttributeType: S
      KeySchema:
        - AttributeName: pipeline_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  BuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/build_function/
      Role: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /build
            Method: post

  DeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/deploy_function/
      Role: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /deploy
            Method: post

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/notifications/
      Role: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /notify
            Method: post

  PipelineManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/pipeline_manager/
      Role: arn:aws:iam::537124961939:role/Adam
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /pipeline
            Method: post
